'use client'
import "@/styles/globals.css";
import type {Metadata} from 'next';
import {fontSans} from '@/config/fonts';
import clsx from "clsx";
import {ReactNode} from "react";

import * as React from "react";
import MainLayout from "@/components/nav/MainLayout";
import Aside from "@/components/nav/Aside";

// export const metadata: Metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
//
// }

export default function Layout({children,}: {
    children: ReactNode
}) {
    return (
        <MainLayout>
            <div className='flex flex-1 overflow-hidden'>
                <Aside/>
                {children}
            </div>

        </MainLayout>
    )
}
