'use client'
import "@/styles/globals.css";
import type {Metadata} from 'next';
import {fontSans} from '@/config/fonts';
import clsx from "clsx";
import {ReactNode} from "react";
import {Layout} from "@/components/layout/layout";
import * as React from "react";

// export const metadata: Metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
//
// }

export default function DashboardLayout({children,}: {
    children: ReactNode
}) {
    return (
        <Layout>
            {children}
        </Layout>
    )
}
