import "@/styles/globals.css";
import type {Metadata} from 'next';
import {Providers} from "./providers";
import {fontSans} from '@/config/fonts';
import clsx from "clsx";
import {ReactNode} from "react";
import {openSocket} from "@/app/actions";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({children,}: {
    children: ReactNode
}) {
    const id = Date.now().toString();
    // await openSocket(id);
    return (
        <html lang="en">
        <body className={clsx("font-sans antialiased", fontSans.className)}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}
