# Generated by Django 5.0.4 on 2024-05-16 18:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'dashboard project',
                'verbose_name_plural': 'dashboard projects',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color_hex', models.CharField(default='#eeeeee', max_length=7, verbose_name='color HEX')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'group permission',
                'verbose_name_plural': 'groups permissions',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'marker',
                'verbose_name_plural': 'markers',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('deactivated', models.BooleanField(default=False, verbose_name='deactivated')),
            ],
            options={
                'verbose_name': 'project member',
                'verbose_name_plural': 'project members',
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'project member group',
                'verbose_name_plural': 'project member groups',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('completed', 'Completed'), ('default', 'Default')], default='default', max_length=10, verbose_name='category')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=10, verbose_name='priority')),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='due date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'task dependency',
                'verbose_name_plural': 'tasks dependencies',
            },
        ),
        migrations.CreateModel(
            name='TaskMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'task marker',
                'verbose_name_plural': 'tasks markers',
                'ordering': ('-created_at',),
            },
        ),
    ]
