# Generated by Django 5.0.4 on 2024-04-11 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('content', models.FileField(upload_to='')),
                ('is_cover', models.BooleanField(default=False, verbose_name='is cover')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('team', 'Team')], default='Private', max_length=10, verbose_name='privacy')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
            },
        ),
        migrations.CreateModel(
            name='BoardBackground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
            ],
            options={
                'verbose_name': 'board background',
                'verbose_name_plural': 'boards backgrounds',
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'board member',
                'verbose_name_plural': 'boards members',
            },
        ),
        migrations.CreateModel(
            name='BoardMemberPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
            ],
            options={
                'verbose_name': 'board member permission',
                'verbose_name_plural': 'board members permissions',
            },
        ),
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
            ],
            options={
                'verbose_name': 'board template',
                'verbose_name_plural': 'boards templates',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
            ],
            options={
                'verbose_name': 'check',
                'verbose_name_plural': 'checks',
            },
        ),
        migrations.CreateModel(
            name='CheckExecutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'check executor',
                'verbose_name_plural': 'checks executors',
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
            ],
            options={
                'verbose_name': 'check list',
                'verbose_name_plural': 'checks lists',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='event title')),
                ('description', models.TextField(verbose_name='event description')),
                ('start_time', models.DateTimeField(verbose_name='event start time')),
                ('end_time', models.DateTimeField(verbose_name='event end time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_ended', models.BooleanField(default=False, verbose_name='is ended')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveIntegerField(default=0, unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'marker',
                'verbose_name_plural': 'markers',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskViewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'task viewer',
                'verbose_name_plural': 'management viewers',
            },
        ),
    ]
