# Generated by Django 5.0.4 on 2024-05-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='users.profile', verbose_name='dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardproject',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dashboard', verbose_name='dashboard'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(through='management.GroupPermission', to='management.permission', verbose_name='permissions'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_projects', to='users.profile', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='marker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='dashboardproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='projects',
            field=models.ManyToManyField(blank=True, through='management.DashboardProject', to='management.project', verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_memberships', to='users.profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_set', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='management.ProjectMember', to='users.profile', verbose_name='members'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='management.projectmember', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='projectmembergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='projectmembergroup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projectmember', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='groups',
            field=models.ManyToManyField(related_name='members', through='management.ProjectMemberGroup', to='management.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='management.projectmember', verbose_name='executors'),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to='management.projectmember', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='management.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.status', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='management.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='from_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='management.task', verbose_name='from task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='to_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='management.task', verbose_name='to task'),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, default=[], through='management.TaskDependency', to='management.task', verbose_name='dependencies'),
        ),
        migrations.AddField(
            model_name='taskmarker',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management.marker', verbose_name='marker'),
        ),
        migrations.AddField(
            model_name='taskmarker',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='task',
            name='markers',
            field=models.ManyToManyField(blank=True, default=[], through='management.TaskMarker', to='management.marker', verbose_name='markers'),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('group', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardproject',
            unique_together={('dashboard', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmembergroup',
            unique_together={('group', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('from_task', 'to_task')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmarker',
            unique_together={('task', 'marker')},
        ),
    ]
