# Generated by Django 5.0.4 on 2024-04-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.profile', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_boards', to='users.profile', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='board',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.boardbackground', verbose_name='background'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(through='management.BoardMember', to='users.profile', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='boardmemberpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.boardmember', verbose_name='board member'),
        ),
        migrations.AddField(
            model_name='boardtemplate',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='checkexecutor',
            name='check_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.check', verbose_name='check'),
        ),
        migrations.AddField(
            model_name='checkexecutor',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='check',
            name='executors',
            field=models.ManyToManyField(through='management.CheckExecutor', to='users.profile', verbose_name='executors'),
        ),
        migrations.AddField(
            model_name='check',
            name='check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.checklist', verbose_name='check list'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.profile', verbose_name='event owner'),
        ),
        migrations.AddField(
            model_name='list',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='management.board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='marker',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='management.board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='boardmemberpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='permissions',
            field=models.ManyToManyField(related_name='members', through='management.BoardMemberPermission', to='management.permission', verbose_name='permissions'),
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.list', verbose_name='list'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tasks', to='users.profile', verbose_name='task owner'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='taskviewer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_viewers', to='management.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='taskviewer',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_tasks', to='users.profile', verbose_name='viewer'),
        ),
        migrations.AddField(
            model_name='task',
            name='viewers',
            field=models.ManyToManyField(through='management.TaskViewer', to='users.profile', verbose_name='task viewers'),
        ),
        migrations.AlterUniqueTogether(
            name='checkexecutor',
            unique_together={('check_box', 'executor')},
        ),
        migrations.AlterUniqueTogether(
            name='boardmemberpermission',
            unique_together={('permission', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='taskviewer',
            unique_together={('viewer', 'task')},
        ),
    ]
