# Generated by Django 5.0.4 on 2024-04-13 01:19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='date_joined',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='code')),
                ('invited_at', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 1, 19, 38, 50026, tzinfo=datetime.timezone.utc), verbose_name='date joined')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is accepted')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='management.board', verbose_name='board')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_got', to='users.profile', verbose_name='recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='users.profile', verbose_name='sender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
