# Generated by Django 5.0.4 on 2024-04-13 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_boardmember_date_joined_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 10, 57, 37, 461683, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('name', 'code')},
        ),
    ]
