# Generated by Django 5.0.4 on 2024-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
