# Generated by Django 5.0.4 on 2024-04-30 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_group_is_default_alter_marker_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last edit'),
        ),
    ]
