# Generated by Django 5.0.4 on 2024-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_invitation_code_remove_invitation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
