# Generated by Django 5.0.4 on 2024-04-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_invitation_invited_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
