# Generated by Django 5.0.4 on 2024-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_delete_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
