# Generated by Django 5.0.4 on 2024-05-03 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_comment_options_alter_marker_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='users.profile', verbose_name='dashboard')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dashboard', verbose_name='dashboard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'dashboard project',
                'verbose_name_plural': 'dashboard projects',
                'unique_together': {('dashboard', 'project')},
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='projects',
            field=models.ManyToManyField(blank=True, through='management.DashboardProject', to='management.project', verbose_name='projects'),
        ),
    ]
