# Generated by Django 5.0.4 on 2024-04-14 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_boardmember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined'),
        ),
    ]
