# Generated by Django 5.0.4 on 2024-05-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_permission_order_remove_project_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sender',
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='management.projectmember', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='dashboardproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='management.project', verbose_name='project'),
        ),
    ]
