# Generated by Django 5.0.4 on 2024-04-17 00:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_boardmember_date_joined'),
        ('permissions', '0001_initial'),
        ('users', '0004_user_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmemberpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='permission'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='permissions',
            field=models.ManyToManyField(related_name='members', through='management.BoardMemberPermission', to='permissions.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='boardmemberpermission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.boardmember', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tasks', to='users.profile', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='viewers',
            field=models.ManyToManyField(through='management.TaskViewer', to='users.profile', verbose_name='viewers'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_workspaces', to='users.profile', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.workspace', verbose_name='workspace'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.workspace', verbose_name='board')),
            ],
            options={
                'verbose_name': 'workspace member',
                'verbose_name_plural': 'workspaces members',
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(through='management.WorkspaceMember', to='users.profile', verbose_name='members'),
        ),
        migrations.CreateModel(
            name='WorkspaceMemberGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.group', verbose_name='group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.workspacemember', verbose_name='member')),
            ],
            options={
                'verbose_name': 'workspace member group',
                'verbose_name_plural': 'workspace members groups',
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='groups',
            field=models.ManyToManyField(related_name='members', through='management.WorkspaceMemberGroup', to='permissions.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='WorkspaceMemberPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.workspacemember', verbose_name='member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='permission')),
            ],
            options={
                'verbose_name': 'workspace member permission',
                'verbose_name_plural': 'workspace members permissions',
                'unique_together': {('permission', 'member')},
            },
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='permissions',
            field=models.ManyToManyField(related_name='workspace_members', through='management.WorkspaceMemberPermission', to='permissions.permission', verbose_name='permissions'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
