# Generated by Django 5.0.4 on 2024-05-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_comment_sender_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardproject',
            options={'ordering': ('order',), 'verbose_name': 'dashboard project', 'verbose_name_plural': 'dashboard projects'},
        ),
    ]
