# Generated by Django 5.0.4 on 2024-04-21 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_boardmemberpermission_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='permissions',
        ),
        migrations.AlterUniqueTogether(
            name='workspacememberpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workspacememberpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='workspacememberpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='check',
            name='executors',
            field=models.ManyToManyField(through='management.CheckExecutor', to='management.boardmember', verbose_name='executors'),
        ),
        migrations.AlterField(
            model_name='checkexecutor',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.boardmember', verbose_name='executor'),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deadline'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('content', models.TextField(verbose_name='content')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.boardmember', verbose_name='sender')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.DeleteModel(
            name='BoardMemberPermission',
        ),
        migrations.DeleteModel(
            name='WorkspaceMemberPermission',
        ),
    ]
