# Generated by Django 5.0.4 on 2024-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_dashboardproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardproject',
            options={'ordering': ('order',), 'verbose_name': 'dashboard project', 'verbose_name_plural': 'dashboard projects'},
        ),
    ]
