# Generated by Django 5.0.4 on 2024-04-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_boardmember_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='deactivated',
            field=models.BooleanField(default=False, verbose_name='deactivated'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='deactivated',
            field=models.BooleanField(default=False, verbose_name='deactivated'),
        ),
    ]
