# Generated by Django 5.0.4 on 2024-04-23 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_boardmember_deactivated_workspacemember_deactivated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskviewer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskviewer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskviewer',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='viewers',
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='management.task', verbose_name='task'),
        ),
        migrations.CreateModel(
            name='TaskExecutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.boardmember', verbose_name='executor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task executor',
                'verbose_name_plural': 'tasks executors',
                'unique_together': {('task', 'executor')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(through='management.TaskExecutor', to='management.boardmember', verbose_name='executors'),
        ),
        migrations.CreateModel(
            name='TaskMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.marker', verbose_name='marker')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task marker',
                'verbose_name_plural': 'tasks markers',
                'unique_together': {('task', 'marker')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='markers',
            field=models.ManyToManyField(through='management.TaskMarker', to='management.marker', verbose_name='markers'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='TaskViewer',
        ),
    ]
