# Generated by Django 5.0.4 on 2024-04-29 16:26

import django.db.models.deletion
import django.utils.timezone
import src.notifications.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='management.project', verbose_name='workspace')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, src.notifications.mixins.InvitationMixin),
        ),
    ]
