# Generated by Django 5.0.4 on 2024-04-13 18:26

import django.db.models.deletion
import src.notifications.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_delete_invitation'),
        ('notifications', '0001_initial'),
        ('users', '0002_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('type', models.CharField(choices=[('board', 'Board'), ('team', 'Team')], default='Board', max_length=10, verbose_name='type')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='management.board', verbose_name='board')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_got', to='users.profile', verbose_name='recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='users.profile', verbose_name='sender')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.team', verbose_name='team')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, src.notifications.mixins.InvitationMixin),
        ),
    ]
