# Generated by Django 5.0.4 on 2024-04-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_boardmemberpermission_permission_and_more'),
        ('notifications', '0002_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='board',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='type',
        ),
        migrations.AddField(
            model_name='invitation',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='management.workspace', verbose_name='workspace'),
        ),
    ]
