# Generated by Django 5.0.4 on 2024-05-03 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_permission_order_remove_project_order_and_more'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expire at')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='uses count')),
                ('max_uses_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='max uses count')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='management.projectmember', verbose_name='creator')),
            ],
            options={
                'verbose_name': 'invitation link',
                'verbose_name_plural': 'invitation links',
            },
        ),
    ]
