# Generated by Django 5.0.4 on 2024-05-16 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import src.users.managers
import src.users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('email_visibility', models.CharField(choices=[('all', 'All'), ('members', 'Members'), ('nobody', 'Nobody')], default='me', max_length=10, verbose_name='who can view email')),
                ('invitation', models.CharField(choices=[('all', 'All'), ('members', 'Members'), ('nobody', 'Nobody')], default='all', max_length=10, verbose_name='who can invite')),
            ],
            options={
                'verbose_name': 'profile settings',
                'verbose_name_plural': 'profile settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='new email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('is_deactivated', models.BooleanField(default=False, editable=False, verbose_name='deactivated')),
                ('delete_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='delete id')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('connections', models.PositiveIntegerField(default=0, editable=False, verbose_name='connections')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', src.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last name')),
                ('banner_color_hex', models.CharField(default='#eeeeee', max_length=7, verbose_name='banner color')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=src.users.models.profile_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
