# Generated by Django 5.0.4 on 2024-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='connections'),
        ),
    ]
