# Generated by Django 5.0.4 on 2024-04-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='own_teams', to='users.profile', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
