# Generated by Django 5.0.4 on 2024-05-11 15:14

import django.core.validators
import src.users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_online_user_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('email_visibility', models.CharField(choices=[('all', 'All'), ('members', 'Members'), ('nobody', 'Nobody')], default='me', max_length=10, verbose_name='who can view email')),
                ('invitation', models.CharField(choices=[('all', 'All'), ('members', 'Members'), ('nobody', 'Nobody')], default='all', max_length=10, verbose_name='who can invite')),
            ],
            options={
                'verbose_name': 'profile settings',
                'verbose_name_plural': 'profile settings',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_color_hex',
            field=models.CharField(default='#FFF', max_length=7, verbose_name='banner color'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=src.users.models.profile_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
