# Generated by Django 5.0.4 on 2024-04-14 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='blocked at')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='blocked_user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='users.profile', verbose_name='blocker')),
            ],
            options={
                'verbose_name': 'blocked profile',
                'verbose_name_plural': 'blocked profiles',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
