# Generated by Django 5.0.4 on 2024-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_invitation_board_remove_invitation_team_and_more'),
        ('users', '0004_user_new_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.AddField(
            model_name='user',
            name='delete_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='delete id'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False, editable=False, verbose_name='deactivated'),
        ),
        migrations.DeleteModel(
            name='BlockedProfile',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
