# Generated by Django 5.0.4 on 2024-04-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_boardmemberpermission_permission_and_more'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color_hex',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='color HEX'),
        ),
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='group',
            name='workspace',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='management.workspace', verbose_name='workspace'),
            preserve_default=False,
        ),
    ]
