import "@/styles/globals.css";
import type {Metadata} from 'next';
import {fontSans} from '@/config/fonts';
import clsx from "clsx";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: 'Auth',
    description: 'Generated by Next.js',

}

export default function AuthLayout({children,}: {
    children: ReactNode
}) {
    return (

        <div>
            {children}
        </div>
    )
}